modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/Wandering-Trades-Manager/issues"
license = "MIT"

[[mods]]
modId = "wanderingtradesmanager"
version = "${version}"
displayName = "Wandering Trades Manager"
authors = "CoolAid48"
credits = "Jeremiah Scottie"
description = '''
Adds a config screen to manage your VT Wandering Trades datapack in-game

Credits:
Vanilla Tweaks: https://vanillatweaks.net
'''

logoFile = "assets/wanderingtradesmanager/icon.png"
